module.exports = {
  content: ["./public/index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
    screens: {
      sm: "480px",
      md: "768px",
      lg: "976px",
      xl: "1440px",
    },
    variants: {
      display: [
        "children",
        "default",
        "children-first",
        "children-last",
        "children-odd",
        "children-even",
        "children-not-first",
        "children-not-last",
        "children-hover",
        "hover",
        "children-focus",
        "focus",
        "children-focus-within",
        "focus-within",
        "children-active",
        "active",
        "children-visited",
        "visited",
        "children-disabled",
        "disabled",
        "responsive",
      ],
    },
  },
  plugins: [require("tailwindcss-children")],
};
